<template>
  <g class="trace-node">
    <g v-if="isRoot"></g>
    <g v-else
       :class="getIsClickableClass()"
       :transform="`translate(${[visTraceNode.x, visTraceNode.y]})`"
       :opacity="visTraceNode.expanded ? 0.3 : 1"
       @click="clickNode">
      <rect class="trace-node-rect"
            :y="-lineHeight / 2"
            :width="width"
            :height="lineHeight"
            :fill="getTraceNodeColor()">
        <title>{{ `${visTraceNode.getSimpleName()}\n` }}
          {{ `${visTraceNode.getTotalStepCnt()} action(s)` }}</title>
      </rect>
      <g :transform="`translate(${[width / 2, 0]})`">
        <rect class="trace-node-text-rect"
              :x="-tipBoxSize.width / 2"
              :y="-tipBoxSize.height / 2"
              :width="tipBoxSize.width"
              :height="tipBoxSize.height"
              :rx="tipBoxSize.height / 2"
              :ry="tipBoxSize.height / 2"
              :stroke="getTraceNodeColor()"
              stroke-width="2"
              fill="white">
          <title>{{ `${visTraceNode.getSimpleName()}\n` }}
            {{ `${visTraceNode.getTotalStepCnt()} action(s)` }}</title>
        </rect>
        <g class="icon-group" :transform="getIconTransform()">
          <svg v-show="iconStatus === IconStatus.LOADING"
               :width="iconSize" :height="iconSize"
               xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background-image: none; display: block; shape-rendering: auto;" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
            <g transform="rotate(0 50 50)">
              <rect x="45.5" y="25" rx="3.68" ry="3.68" width="9" height="16" fill="#575757">
                <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.875s" repeatCount="indefinite"></animate>
              </rect>
            </g><g transform="rotate(45 50 50)">
            <rect x="45.5" y="25" rx="3.68" ry="3.68" width="9" height="16" fill="#575757">
              <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.75s" repeatCount="indefinite"></animate>
            </rect>
          </g><g transform="rotate(90 50 50)">
            <rect x="45.5" y="25" rx="3.68" ry="3.68" width="9" height="16" fill="#575757">
              <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.625s" repeatCount="indefinite"></animate>
            </rect>
          </g><g transform="rotate(135 50 50)">
            <rect x="45.5" y="25" rx="3.68" ry="3.68" width="9" height="16" fill="#575757">
              <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.5s" repeatCount="indefinite"></animate>
            </rect>
          </g><g transform="rotate(180 50 50)">
            <rect x="45.5" y="25" rx="3.68" ry="3.68" width="9" height="16" fill="#575757">
              <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.375s" repeatCount="indefinite"></animate>
            </rect>
          </g><g transform="rotate(225 50 50)">
            <rect x="45.5" y="25" rx="3.68" ry="3.68" width="9" height="16" fill="#575757">
              <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.25s" repeatCount="indefinite"></animate>
            </rect>
          </g><g transform="rotate(270 50 50)">
            <rect x="45.5" y="25" rx="3.68" ry="3.68" width="9" height="16" fill="#575757">
              <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.125s" repeatCount="indefinite"></animate>
            </rect>
          </g><g transform="rotate(315 50 50)">
            <rect x="45.5" y="25" rx="3.68" ry="3.68" width="9" height="16" fill="#575757">
              <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="0s" repeatCount="indefinite"></animate>
            </rect>
          </g>
            <!-- [ldio] generated by https://loading.io/ --></svg>
          <svg v-show="iconStatus === IconStatus.COLLAPSED"
               :width="iconSize" :height="iconSize"
               t="1689089454988" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="1591" id="mx_n_1689089454990"><path d="M446.293333 768a95.146667 95.146667 0 0 1-38.826666-8.533333 75.093333 75.093333 0 0 1-44.8-67.84V332.373333A75.093333 75.093333 0 0 1 407.466667 264.533333a89.6 89.6 0 0 1 94.293333 11.093334l217.6 179.626666a72.533333 72.533333 0 0 1 0 113.493334l-217.6 179.626666a87.893333 87.893333 0 0 1-55.466667 19.626667z" p-id="1592" fill="#575757"></path></svg>
          <svg v-show="iconStatus === IconStatus.EXPANDED"
               :width="iconSize" :height="iconSize"
               t="1689089508611" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="3340"><path d="M512 725.333333a73.386667 73.386667 0 0 1-56.746667-27.306666l-179.626666-217.6a89.6 89.6 0 0 1-11.093334-94.293334A75.093333 75.093333 0 0 1 332.373333 341.333333h359.253334a75.093333 75.093333 0 0 1 67.84 44.8 89.6 89.6 0 0 1-11.093334 94.293334l-179.626666 217.6A73.386667 73.386667 0 0 1 512 725.333333z" p-id="3341" fill="#575757"></path></svg>
        </g>
        <text class="trace-node-text"
              :dx="isExpandable ? textLeftForIcon : 0"
              :dy="2"
              :font-size="fontSize"
              dominant-baseline="middle"
              text-anchor="middle">{{ traceNodeText }}
        </text>
      </g>

    </g>
    <g v-if="visTraceNode.expanded" class="children-group">
      <TraceNavNode v-for="(child, idx) in visTraceNode.children"
                    :key="idx"
                    :vis-trace-tree="visTraceTree"
                    :vis-trace-node="child"
                    :node-idx="idx"/>
    </g>
  </g>
</template>

<script>
/* eslint-disable */
import {mapMutations, mapState} from 'vuex'
import {getLimitedString, getTextSize} from "@/utils/Layout"
import {VisTraceTree} from "@/js/trace/VisTraceTree"
import {VisTraceNode} from "@/js/trace/VisTraceNode"
import Color from "color"

export default {
  name: 'TraceNavNode',
  components: {},
  props: {
    visTraceTree: VisTraceTree,
    visTraceNode: VisTraceNode,
  },
  data() {
    const IconStatus = {
      NONE: 'none',
      LOADING: 'loading',
      EXPANDED: 'expanded',
      COLLAPSED: 'collapsed',
    }
    return {
      textLeftForIcon: 8,
      IconStatus,
      iconStatus: IconStatus.NONE,
    }
  },
  mounted() {
    this.iconStatus = this.computeIconStatus()
  },
  methods: {
    ...mapMutations('trace', [
      'toggleTraceNode',
    ]),
    getIsClickableClass() {
      return this.isExpandable ? { 'clickable': true } : {}
    },
    computeIconStatus() {
      if (this.visTraceNode.children.length === 0) {
        return this.IconStatus.NONE
      }
      if (this.visTraceNode.expanded) {
        return this.IconStatus.EXPANDED
      } else {
        return this.IconStatus.COLLAPSED
      }
    },
    getIconTransform() {
      const x = -this.tipBoxSize.width / 2
      const y = -this.iconSize / 2
      return `translate(${x},${y})`
    },
    clickNode() {
      console.log(this.visTraceNode)
      if (this.visTraceNode.children.length === 0) {
        return
      }
      this.iconStatus = this.IconStatus.LOADING
      setTimeout(() => {
        this.toggleTraceNode(this.visTraceNode)
        this.iconStatus = this.computeIconStatus()
      }, 10)
    },
    getTraceNodeColor() {
      const color = this.visTraceTree.getColor(this.visTraceNode)
      // return new Color(color).lighten(0.4)
      return color
    },
    getVisTimeCost(timeCost) {
      // timeCost is in ns
      if (timeCost < 1000) {
        return `${timeCost} ns`
      } else if (timeCost < 1000000) {
        return `${(timeCost / 1000).toFixed(2)} us`
      } else if (timeCost < 1000000000) {
        return `${(timeCost / 1000000).toFixed(2)} ms`
      } else {
        return `${(timeCost / 1000000000).toFixed(2)} s`
      }
    }
  },
  computed: {
    ...mapState('trace', {
      rowHeight: state => state.configV3.nav.rowHeight,
      fontSize: state => state.configV3.nav.fontSize,
    }),
    isRoot() {
      return this.visTraceNode.isRoot
    },
    isExpandable() {
      return this.visTraceNode.children.length > 0
    },
    iconSize() {
      return this.textSize.height
    },
    width() {
      return this.visTraceNode.width
    },
    lineHeight() {
      return this.visTraceNode.lineHeight
    },
    traceNodeText() {
      const textLeftForIcon = this.isExpandable ? this.textLeftForIcon : 0
      const padding = 40
      if (this.visTraceNode.isGroup) {
        let str = this.visTraceNode.getSimpleName()

        let countStr = `(${this.visTraceNode.children.length})`
        const {width: countStrWidth} = getTextSize(countStr, this.fontSize)

        const strWidth = this.width - textLeftForIcon - padding * 2 - countStrWidth
        str = getLimitedString('Group of ' + str, strWidth, this.fontSize)

        return `${str} ${countStr}`

      } else {
        let str = this.visTraceNode.getSimpleName()
        const strWidth = this.width - textLeftForIcon - padding * 2
        str = getLimitedString(str, strWidth, this.fontSize)
        return str
      }
    },
    textSize() {
      return getTextSize(this.traceNodeText, this.fontSize)
    },
    tipBoxSize() {
      return {
        width: this.textSize.width + this.textLeftForIcon + this.textSize.height,
        height: this.textSize.height,
      }
    },
  }
}
</script>

<style scoped>
.trace-node {
}

.clickable {
  cursor: pointer;
}

.trace-node-text {
  user-select: none;
  pointer-events: none;
}
</style>
